In [1]:
from pybaseball import batting_stats_range
import pandas as pd

In [7]:
stats = batting_stats_range("2023-03-30", "2023-05-30")

In [16]:
season_stats = batting_stats_range("2023-03-30", "2023-10-01")

In [21]:
filtered_stats = stats[stats['PA'] > 100]
filtered_season_stats = season_stats[season_stats['PA'] > 100]
filtered_stats.rename(columns={'OPS':'Early OPS'}, inplace=True)

C:\Users\16086\AppData\Local\Temp\ipykernel_15984\4183900622.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_stats.rename(columns={'OPS':'Early OPS'}, inplace=True)

In [22]:
filtered_stats.sort_values(by='Early OPS', ascending=False)

,Name,Age,#days,Lev,Tm,G,PA,AB,R,H,...,SH,SF,GDP,SB,CS,BA,OBP,SLG,Early OPS,mlbID
242,Aaron Judge,31,247,Maj-AL,New York,46,201,165,41,50,...,0,3,2,3,1,0.303,0.413,0.691,1.104,592450
133,Yandy D\xc3\xadaz,31,248,Maj-AL,Tampa Bay,46,200,169,37,54,...,0,1,6,0,0,0.320,0.420,0.598,1.018,650490
168,Freddie Freeman,33,247,Maj-NL,Los Angeles,56,257,224,47,77,...,0,3,3,6,1,0.344,0.416,0.589,1.006,518692
17,Yordan \xc3\x81lvarez,26,247,Maj-AL,Houston,48,208,173,35,50,...,0,2,5,0,0,0.289,0.399,0.601,1.000,670541
3,Ronald Acuna Jr.,25,247,Maj-NL,Atlanta,55,249,217,48,70,...,0,1,4,21,4,0.323,0.406,0.553,0.959,660670
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
428,Jean Segura,33,247,Maj-NL,Miami,47,177,162,11,32,...,1,0,10,3,2,0.198,0.261,0.228,0.490,516416
247,Tony Kemp,31,248,Maj-AL,Oakland,46,162,142,9,22,...,2,1,4,2,1,0.155,0.244,0.211,0.455,643393
536,Kolten Wong,32,250,Maj-AL,Seattle,36,120,106,11,17,...,0,1,0,0,1,0.160,0.250,0.189,0.439,543939
343,Austin Nola,33,247,Maj-NL,San Diego,40,119,100,6,13,...,3,0,2,0,0,0.130,0.250,0.180,0.430,543592
61,Jackie Bradley Jr.,33,248,Maj-AL,Kansas City,40,107,99,10,14,...,1,0,3,0,0,0.141,0.198,0.222,0.420,598265

In [23]:
stat_df = filtered_season_stats.merge(filtered_stats[['Name', 'Early OPS']], on='Name', how='left')

In [25]:
stat_df = stat_df.dropna(subset=['Early OPS'])

In [30]:
stat_df['OPS Diff'] = abs(stat_df['OPS'] - stat_df['Early OPS'])

C:\Users\16086\AppData\Local\Temp\ipykernel_15984\3945377760.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stat_df['OPS Diff'] = abs(stat_df['OPS'] - stat_df['Early OPS'])

In [32]:
stat_df.sort_values(by='OPS Diff', ascending=False).to_csv('sorted_stats.csv')